{% set name = "autoconf-archive" %}
{% set version = "2019.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/autoconf-archive/{{ name }}-{{ version }}.tar.xz
  sha256: d5a32a82cb757c0026f2394d86a42fb5e3a2a6f8e89ad91904e33ce1cff092ac

build:
  number: 1
  noarch: generic
  skip: True  # [win]

requirements:
  build:
    - autoconf
  run:
    - autoconf

test:
  commands:
    - test -d ${PREFIX}/share/autoconf-archive

about:
  home: https://savannah.gnu.org/projects/autoconf-archive/
  license: GPL-3.0
  license_family: GPL
  summary: Collection of over 500 reusable autoconf macros

extra:
  recipe-maintainers:
    - egpbos
    - mcs07
