{% set name = "autoconf-archive" %}
{% set version = "2022.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: 7b5079fbe139b55903e6efdb4f67700e49aeaca2c0cb10d65345f5f8b70d89e7

build:
  number: 0
  noarch: generic
  skip: True  # [win]

requirements:
  build:
    - autoconf
  run:
    - autoconf

test:
  commands:
    - test -f ${PREFIX}/share/aclocal/ax_absolute_header.m4

about:
  home: https://savannah.gnu.org/projects/autoconf-archive/
  license: GPL-3.0
  license_family: GPL
  summary: Collection of over 500 reusable autoconf macros

extra:
  recipe-maintainers:
    - egpbos
    - mcs07
