travis:
  secure:
    BINSTAR_TOKEN: pgII+L71bVkU4gvabfNGcjm3MQXQyH1DxAUB8z3cZJKC+2dw34zyj68hzYL8APfgfzjTVmMe18dELIrjzjVipA8/+iEFFZKbheGK6/QwKn2ODwZS00rz41LZU0f2/4OSP2E4tOJgMF114cNKsbdt2tL4Az90S9wNoWQyssgnhvc/OKODFK+FmHBXL2XTHqMhcQcQQSJWG6ciG89pqCmXbM0oUuITqoLdA/STbf78xbIxivHi5FQnIjujSpFcFKcB/ea3dJSLQiENZPUtGL+Q3iBgGpG9t9EU24HQOjdqRkmrIgKPXLaRXuDuk6scrPVeZEQguhl5O3NyXD4p1duLkBZwj34nrmfqkVtJTzCREQcOts3JGEF7Z8Nj/JBXLq8lZc4kfox3FvCePsJXAts9au+vctOE8DFz2DvyA9TENkzWV0Ujo5ABnWWrq2hxoeVBwzelW2RFIoWthJVK/eDjZY0lym1MkUbTWp1z+kwUG/T/Y2Oug3chtutY2212H4sBm0e6SEP0WETPWhWivyrX20d6nz0pgx8qapOO14uIWENA5uJKl+4xTUwOBim9zh6+qkxAPjYpCCkwSLsG5ZLfcIy2QQIe1L9yA34xEjjFomFA9Tx2KODHtgmSdjK2VseeqPGBAssv8aTYPUE8pC9EYK4ScqedVmYxCOdehJuSt00=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
